CREATE TABLE PAIS(
	id INT PRIMARY KEY,
	nombre VARCHAR2(50)
);

CREATE TABLE AEROPUERTO (
	id INT PRIMARY KEY,
	nombre VARCHAR2(50) NOT NULL,
	id_pais INT NOT NULL,
    id_principal INT NULL
);

ALTER TABLE AEROPUERTO ADD FOREIGN KEY (id_pais) REFERENCES PAIS(id);
ALTER TABLE AEROPUERTO ADD FOREIGN KEY (id_principal) REFERENCES AEROPUERTO(id);

-- PAIS
INSERT INTO PAIS VALUES(1,'México');
INSERT INTO PAIS VALUES(2,'Belice');
INSERT INTO PAIS VALUES(3,'Costa Rica');
INSERT INTO PAIS VALUES(4,'El Salvador');
INSERT INTO PAIS VALUES(5,'Guatemala');
INSERT INTO PAIS VALUES(6,'Honduras');
INSERT INTO PAIS VALUES(7,'Nicaragua');
INSERT INTO PAIS VALUES(8,'Panamá');
INSERT INTO PAIS VALUES(9,'Argentina');
INSERT INTO PAIS VALUES(10,'Bolivia');
INSERT INTO PAIS VALUES(11,'Brasil');
INSERT INTO PAIS VALUES(12,'Chile');
INSERT INTO PAIS VALUES(13,'Colombia');
INSERT INTO PAIS VALUES(14,'Ecuador');
INSERT INTO PAIS VALUES(15,'Guyana');
INSERT INTO PAIS VALUES(16,'Guyana Francesa');
INSERT INTO PAIS VALUES(17,'Paraguay');
INSERT INTO PAIS VALUES(18,'Perú');
INSERT INTO PAIS VALUES(19,'Suriname');
INSERT INTO PAIS VALUES(20,'Uruguay');
INSERT INTO PAIS VALUES(21,'Venezuela');

INSERT INTO AEROPUERTO VALUES(1,'El Valle',15,NULL);
INSERT INTO AEROPUERTO VALUES(2,'Oranjestad',11,NULL);
INSERT INTO AEROPUERTO VALUES(3,'Hamilton',8,NULL);
INSERT INTO AEROPUERTO VALUES(4,'Kralendijk',9,NULL);
INSERT INTO AEROPUERTO VALUES(5,'Willemstad',13,NULL);
INSERT INTO AEROPUERTO VALUES(6,'Nuuk',10,NULL);
INSERT INTO AEROPUERTO VALUES(7,'Basse-Terre',2,NULL);
INSERT INTO AEROPUERTO VALUES(8,'Cayena',9,NULL);
INSERT INTO AEROPUERTO VALUES(9,'George Town',15,NULL);
INSERT INTO AEROPUERTO VALUES(10,'King Edward Point',15,NULL);
INSERT INTO AEROPUERTO VALUES(11,'Puerto Argentino',7,NULL);
INSERT INTO AEROPUERTO VALUES(12,'Mountainburn Town',16,NULL);
INSERT INTO AEROPUERTO VALUES(13,'Road Town',13,NULL);
INSERT INTO AEROPUERTO VALUES(14,'Carlota Amalia',7,NULL);
INSERT INTO AEROPUERTO VALUES(15,'Brades',9,NULL);
INSERT INTO AEROPUERTO VALUES(16,'San Juan',4,NULL);
INSERT INTO AEROPUERTO VALUES(17,'The Bottom',7,NULL);
INSERT INTO AEROPUERTO VALUES(18,'Gustavia',4,NULL);
INSERT INTO AEROPUERTO VALUES(19,'Oranjestad',5,NULL);
INSERT INTO AEROPUERTO VALUES(20,'San Pedro',10,NULL);

COMMIT;