CREATE TABLE EQUIPO (
id INT PRIMARY KEY,
nombre VARCHAR2(32)
);

CREATE TABLE INTEGRANTE (
id INT PRIMARY KEY,
nombre VARCHAR (64),
oficina INT,
id_cargo INT,
id_equipo INT,
id_lider INT NULL
);


ALTER TABLE INTEGRANTE ADD FOREIGN KEY (id_equipo) REFERENCES EQUIPO (id);
ALTER TABLE INTEGRANTE ADD FOREIGN KEY (id_lider) REFERENCES INTEGRANTE (id);


INSERT INTO EQUIPO VALUES(1,'Tiempo apurado');
INSERT INTO EQUIPO VALUES(2,'Teletrabajo');
INSERT INTO EQUIPO VALUES(3,'La capa de los héroes');
INSERT INTO EQUIPO VALUES(4,'Dragon work');

INSERT INTO INTEGRANTE VALUES(1,'Aristotle Pollard',1,7,1,null);
INSERT INTO INTEGRANTE VALUES(2,'Ocean Greer',1,4,1,null);
INSERT INTO INTEGRANTE VALUES(3,'Macaulay Key',4,5,1,null);
INSERT INTO INTEGRANTE VALUES(4,'Chester Vang',1,10,1,null);
INSERT INTO INTEGRANTE VALUES(5,'Kylan Hughes',5,2,1,null);
INSERT INTO INTEGRANTE VALUES(6,'David Hopkins',2,1,2,null);
INSERT INTO INTEGRANTE VALUES(7,'Addison Cameron',5,2,2,null);
INSERT INTO INTEGRANTE VALUES(8,'Hayes Davidson',1,1,2,null);
INSERT INTO INTEGRANTE VALUES(9,'Miriam Figueroa',2,4,2,null);
INSERT INTO INTEGRANTE VALUES(10,'Brady Poole',2,7,2,null);
INSERT INTO INTEGRANTE VALUES(11,'Constance Bray',3,8,3,null);
INSERT INTO INTEGRANTE VALUES(12,'Kyla Hale',5,6,3,null);
INSERT INTO INTEGRANTE VALUES(13,'Anne Franco',1,9,3,null);
INSERT INTO INTEGRANTE VALUES(14,'Allistair Barr',5,6,3,null);
INSERT INTO INTEGRANTE VALUES(15,'Alea Wade',5,6,3,null);
INSERT INTO INTEGRANTE VALUES(16,'Tad Whitaker',2,2,4,null);
INSERT INTO INTEGRANTE VALUES(17,'Malachi Long',3,5,4,null);
INSERT INTO INTEGRANTE VALUES(18,'Alec Vega',4,2,4,null);
INSERT INTO INTEGRANTE VALUES(19,'Chelsea Leach',4,7,4,null);
INSERT INTO INTEGRANTE VALUES(20,'Joelle Nolan',2,5,4,null);

COMMIT;

SELECT * FROM EQUIPO;
SELECT * FROM INTEGRANTE;

