CREATE TABLE CATEGORIA(
    id INT PRIMARY KEY,
    nombre VARCHAR2(32)
);

CREATE TABLE VIGILANTE (
    id INT PRIMARY KEY,
    nombre VARCHAR2(128),
    fecha_contrato DATE,
    id_categoria INT,
    id_coordinador INT
);

CREATE TABLE registro_coordinadores (
    coordinador INT,
    fecha DATE
);

ALTER TABLE registro_coordinadores ADD PRIMARY KEY (coordinador, fecha);

ALTER TABLE VIGILANTE ADD FOREIGN KEY (id_categoria) REFERENCES CATEGORIA (id);
ALTER TABLE VIGILANTE ADD FOREIGN KEY (id_coordinador) REFERENCES VIGILANTE (id);

INSERT INTO CATEGORIA VALUES(1,'En proceso de inducción');
INSERT INTO CATEGORIA VALUES(2,'Principiante');
INSERT INTO CATEGORIA VALUES(3,'Intermedio');
INSERT INTO CATEGORIA VALUES(4,'Avanzado');
INSERT INTO CATEGORIA VALUES(5,'Experto');

INSERT INTO VIGILANTE VALUES(1,'Irene Callahan',TO_DATE('11/04/1991', 'DD/MM/YYYY'), 4, NULL);
INSERT INTO VIGILANTE VALUES(2,'Emerson Lott',TO_DATE('25/01/1999', 'DD/MM/YYYY'), 4, NULL);
INSERT INTO VIGILANTE VALUES(3,'Aaron Wolf',TO_DATE('08/03/2003', 'DD/MM/YYYY'), 5, NULL);
INSERT INTO VIGILANTE VALUES(4,'Venus Bray',TO_DATE('15/10/1996', 'DD/MM/YYYY'), 5, NULL);
INSERT INTO VIGILANTE VALUES(5,'Levi Cochran',TO_DATE('05/12/2005', 'DD/MM/YYYY'), 4, NULL);
INSERT INTO VIGILANTE VALUES(6,'Hammett Franklin',TO_DATE('01/01/1999', 'DD/MM/YYYY'), 2, NULL);
INSERT INTO VIGILANTE VALUES(7,'Patience Hammond',TO_DATE('21/02/1991', 'DD/MM/YYYY'), 2, NULL);
INSERT INTO VIGILANTE VALUES(8,'Quinn Duncan',TO_DATE('27/06/1989', 'DD/MM/YYYY'), 2, NULL);
INSERT INTO VIGILANTE VALUES(9,'Stephen Pierce',TO_DATE('23/02/1988', 'DD/MM/YYYY'), 3, NULL);
INSERT INTO VIGILANTE VALUES(10,'Vladimir Knight',TO_DATE('20/06/1990', 'DD/MM/YYYY'), 2, NULL);
INSERT INTO VIGILANTE VALUES(11,'Kirk Hendricks',TO_DATE('01/02/2006', 'DD/MM/YYYY'), 2, NULL);
INSERT INTO VIGILANTE VALUES(12,'Moses Travis',TO_DATE('20/11/1988', 'DD/MM/YYYY'), 1, NULL);
INSERT INTO VIGILANTE VALUES(13,'Nyssa Campos',TO_DATE('19/10/1995', 'DD/MM/YYYY'), 1, NULL);
INSERT INTO VIGILANTE VALUES(14,'Oleg Black',TO_DATE('26/05/1993', 'DD/MM/YYYY'), 3, NULL);
INSERT INTO VIGILANTE VALUES(15,'Damon Serrano',TO_DATE('06/02/1995', 'DD/MM/YYYY'), 1, NULL);
INSERT INTO VIGILANTE VALUES(16,'Raven Wells',TO_DATE('25/06/1997', 'DD/MM/YYYY'), 2, NULL);
INSERT INTO VIGILANTE VALUES(17,'Amy Copeland',TO_DATE('15/03/2005', 'DD/MM/YYYY'), 1, NULL);
INSERT INTO VIGILANTE VALUES(18,'Warren Conner',TO_DATE('27/05/2004', 'DD/MM/YYYY'), 2, NULL);
INSERT INTO VIGILANTE VALUES(19,'Madison Gibson',TO_DATE('19/08/1991', 'DD/MM/YYYY'), 3, NULL);
INSERT INTO VIGILANTE VALUES(20,'Lewis Whitfield',TO_DATE('04/10/2000', 'DD/MM/YYYY'), 1, NULL);
INSERT INTO VIGILANTE VALUES(21,'Gareth Mcintosh',TO_DATE('02/01/2001', 'DD/MM/YYYY'), 2, NULL);
INSERT INTO VIGILANTE VALUES(22,'Amery Stephens',TO_DATE('14/07/1999', 'DD/MM/YYYY'), 2, NULL);
INSERT INTO VIGILANTE VALUES(23,'Sonia Serrano',TO_DATE('13/10/1995', 'DD/MM/YYYY'), 3, NULL);
INSERT INTO VIGILANTE VALUES(24,'Damon Wilkinson',TO_DATE('23/06/2001', 'DD/MM/YYYY'), 2, NULL);
INSERT INTO VIGILANTE VALUES(25,'Neve Noel',TO_DATE('13/02/2000', 'DD/MM/YYYY'), 1, NULL);


COMMIT;

SELECT * FROM CATEGORIA;
SELECT * FROM VIGILANTE;


